package com.employeeintelligence.api.dto;

public record EmployeeResponse(
        Long id,
        String name,
        String department,
        String jobRole,
        Integer age,
        String attrition,
        String businessTravel,
        Integer dailyRate,
        Integer distanceFromHome,
        Integer education,
        String educationField,
        Integer employeeCount,
        Integer employeeNumber,
        Integer environmentSatisfaction,
        String gender,
        Integer hourlyRate,
        Integer jobInvolvement,
        Integer jobLevel,
        Integer jobSatisfaction,
        String maritalStatus,
        Integer monthlyIncome,
        Integer monthlyRate,
        Integer numCompaniesWorked,
        String over18,
        String overTime,
        Integer percentSalaryHike,
        Integer performanceRating,
        Integer relationshipSatisfaction,
        Integer standardHours,
        Integer stockOptionLevel,
        Integer totalWorkingYears,
        Integer trainingTimesLastYear,
        Integer workLifeBalance,
        Integer yearsAtCompany,
        Integer yearsInCurrentRole,
        Integer yearsSinceLastPromotion,
        Integer yearsWithCurrManager) {
}
